### ISSUE TITLE
Fetching origin error: pathspec '*' did not match any file(s) known to git

### ISSUE THREAD

**Issue by nimrossum** [platisd/bad-commit-message-blocker#6] opened 2021-02-13 12:43 UTC
Hello, really cool project! 

I am experiencing an error when running this as a GitHub action:

```
Fetching origin
error: pathspec 'dotnet-refactor' did not match any file(s) known to git
```

This is my workflow file:

```yaml
name: Bad commit message blocker
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Bad commit message blocker
        uses: platisd/bad-commit-message-blocker@1.0.0
```

**Comment by platisd** [comment] 2021-02-13 12:47
Hi!
Are you using it in a public project? Do you happen to have any link to the logs?

**Comment by platisd** [comment] 2021-02-13 15:51
Also, are you passing the `github_token`? The minimum workflow should look something like this:

```yaml
name: Bad commit message blocker
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Bad commit message blocker
        uses: platisd/bad-commit-message-blocker@1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by nimrossum** [comment] 2021-02-16 12:18
Strange, it used to work perfectly fine, without a token.

You can see the logging here:
https://github.com/themagicstrings/twooter/actions

**Comment by platisd** [comment] 2021-02-16 17:59
Alright thanks for the link, it helped a lot and I believe I reproduced it. The following should fix it:

```yaml
name: Bad commit message blocker
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Bad commit message blocker
        uses: platisd/bad-commit-message-blocker@1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          remote_branch: "main"
```
Long story short, the problem is that there is no `master` branch, in your case it is called `main`.
The **very strange** thing is that `github_token` and `remote_branch` are supposed to be **required** attributes, so I am very surprised that they are not required for the Action to run in the first place.
In your case, while apparently `github_token` is not necessary (possibly because it's a public repository, this used to not be the case in the past), `remote_branch` is, since the default value used by the script is `master`.

Can you please try the fix out and let me know?

**Comment by nimrossum** [comment] 2021-02-17 14:49
Thank you for helping!

That must be it, we recently renamed the main branch, and it worked with master.

I will try to use the suggested workflow file.

I think you are right about the token not being needed for readonly actions on public repositories.

**Comment by nimrossum** [comment] 2021-02-17 14:52
Will the "remote-branch" field make it only run on the main branch? I would like to run it on other branches as well.

**Comment by platisd** [comment] 2021-02-17 14:55
> Will the "remote-branch" field make it only run on the main branch? I would like to run it on other branches as well.

It should certainly work in the other branches and I believe on `main` too. Overall, it would work exactly as when you had your default branch named as `master`.

**Comment by nimrossum** [comment] 2021-02-17 15:01
I just tried to run it without the token, it seems to work:
https://github.com/themagicstrings/twooter/actions/runs/575175617/workflow
https://github.com/themagicstrings/twooter/runs/1919529503?check_suite_focus=true

**Comment by platisd** [comment] 2021-02-17 15:02
Yeah, I also noticed that it worked without the token. Perhaps it's nowadays only necessary for private repositories.

**Comment by nimrossum** [comment] 2021-02-17 15:15
It now works perfectly. 
https://github.com/themagicstrings/twooter/runs/1919693819?check_suite_focus=true

Thanks for all the help :)

**Comment by platisd** [comment] 2021-02-17 15:22
> I only enabled the following permissions for the token:

You don't even need to add the token or give any special permissions to it by the way. GitHub produces a default one, so if you write it as `${{ secrets.GITHUB_TOKEN }}` you are set. That is, even if you needed in and in your case you apparently don't, so you can skip it all together.

The run you sent was run with the old workflow file, so yeah, I guess you figured it out while I was typing this answer. :grin: 



> It now works perfectly.
> https://github.com/themagicstrings/twooter/runs/1919693819?check_suite_focus=true
> 
> Thanks for all the help :)

Great to hear! :+1: :rocket: 

I will close this issue, if you need further assistance feel free to reopen it or create new ones.

**Closed as completed by platisd** 2021-02-17 15:22 UTC
